version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci --cache .npm --prefer-offline

  pre_build:
    commands:
      - echo Checking Node.js version...
      - node --version
      - npm --version
      - npm install -g react-scripts

  build:
    commands:
      - echo Building application...
      - npm run build

  post_build:
    commands:
      - echo Build completed!

artifacts:
  files:
    - 'build/**/*'
    - 'package.json'
    - 'package-lock.json'
  discard-paths: no
  base-directory: build

cache:
  paths:
    - 'node_modules/**/*'